/**
 * seedBrcClauses — seeds the clause library for a compliance standard.
 * Libraries: BRCGS Packaging Issue 7 (representative subset), ISO 9001:2015,
 * ISO 14001:2015 and ISO 45001:2018 (paraphrased clause summaries — consult
 * the published standards for authoritative text).
 * Admin-only. Idempotent — will not duplicate if clauses for the standard
 * already exist. Call with: { standard: "iso_9001" } etc.
 */
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// A representative subset of BRCGS Packaging Material Standard Issue 7 clauses
const BRCGS_PACKAGING_CLAUSES = [
  // Section 1 — Senior Management Commitment
  { clause_number: '1.1', parent_clause_number: null, title: 'Senior Management Commitment and Continual Improvement', description: 'The site\'s senior management shall demonstrate they are committed to the development of a food safety culture and the implementation of the requirements of the Standard.', evidence_requirement: 'Management meeting minutes, signed commitment statement, policy documents', is_fundamental: true, display_order: 10 },
  { clause_number: '1.1.1', parent_clause_number: '1.1', title: 'Food Safety and Quality Policy', description: 'The site shall have a documented food safety and quality policy, signed by the current site general manager or equivalent.', evidence_requirement: 'Signed quality policy document with review dates', is_fundamental: false, display_order: 11 },
  { clause_number: '1.1.2', parent_clause_number: '1.1', title: 'Management Review', description: 'Senior management shall review the food safety plan and quality management system at least annually.', evidence_requirement: 'Management review meeting minutes, agenda, action tracker', is_fundamental: false, display_order: 12 },
  { clause_number: '1.2', parent_clause_number: null, title: 'Organisational Structure', description: 'The site shall have a clear organisational structure with defined responsibilities for food safety and quality.', evidence_requirement: 'Organisation chart, job descriptions', is_fundamental: false, display_order: 20 },

  // Section 2 — Hazard and Risk Management
  { clause_number: '2.1', parent_clause_number: null, title: 'HACCP Food Safety Plan', description: 'The site shall have a documented food safety plan based on Codex Alimentarius HACCP principles.', evidence_requirement: 'HACCP study documentation, hazard analysis worksheets, CCP records', is_fundamental: true, display_order: 30 },
  { clause_number: '2.1.1', parent_clause_number: '2.1', title: 'HACCP Team', description: 'A multidisciplinary HACCP team shall be established including a designated HACCP team leader.', evidence_requirement: 'HACCP team list, training records, team leader competence evidence', is_fundamental: false, display_order: 31 },
  { clause_number: '2.2', parent_clause_number: null, title: 'Hazard Analysis', description: 'A full hazard analysis shall be completed for all materials, processes, and products.', evidence_requirement: 'Hazard analysis worksheets, raw material hazard assessments', is_fundamental: false, display_order: 40 },
  { clause_number: '2.3', parent_clause_number: null, title: 'Critical Control Points', description: 'All critical control points shall be identified and documented with critical limits, monitoring procedures and corrective actions.', evidence_requirement: 'CCP monitoring records, critical limit validation evidence', is_fundamental: false, display_order: 50 },

  // Section 3 — Food Safety and Quality Management System
  { clause_number: '3.1', parent_clause_number: null, title: 'Food Safety and Quality Manual', description: 'The site shall maintain a food safety and quality manual covering all requirements of the Standard.', evidence_requirement: 'Quality manual, document control register', is_fundamental: false, display_order: 60 },
  { clause_number: '3.2', parent_clause_number: null, title: 'Document Control', description: 'The site shall have a documented procedure for the control of documents and records.', evidence_requirement: 'Document control procedure, master document list with version numbers', is_fundamental: false, display_order: 70 },
  { clause_number: '3.3', parent_clause_number: null, title: 'Record Completion and Maintenance', description: 'Records shall be legible, maintained in good condition, and retrievable.', evidence_requirement: 'Sample completed records, records retention schedule', is_fundamental: false, display_order: 80 },
  { clause_number: '3.4', parent_clause_number: null, title: 'Internal Audits', description: 'Internal audits shall be carried out at least annually against all clauses of the Standard.', evidence_requirement: 'Internal audit schedule, completed audit reports, close-out evidence', is_fundamental: false, display_order: 90 },
  { clause_number: '3.5', parent_clause_number: null, title: 'Supplier and Material Approval', description: 'The site shall have a documented procedure for the approval and monitoring of suppliers of materials and services.', evidence_requirement: 'Approved supplier list, supplier assessments, questionnaires or audit reports', is_fundamental: false, display_order: 100 },
  { clause_number: '3.6', parent_clause_number: null, title: 'Specifications', description: 'There shall be adequate specifications for all materials and products.', evidence_requirement: 'Raw material specifications, finished product specifications, packaging specifications', is_fundamental: false, display_order: 110 },
  { clause_number: '3.7', parent_clause_number: null, title: 'Corrective and Preventive Action', description: 'The site shall have a procedure to investigate and address the root cause of non-conformances.', evidence_requirement: 'CAPA register, investigation records, close-out verification', is_fundamental: false, display_order: 120 },
  { clause_number: '3.8', parent_clause_number: null, title: 'Control of Non-Conforming Product', description: 'The site shall have a documented procedure for the control of non-conforming materials and product.', evidence_requirement: 'Non-conforming product procedure, segregation records, disposition records', is_fundamental: false, display_order: 130 },
  { clause_number: '3.9', parent_clause_number: null, title: 'Complaints Handling', description: 'There shall be a system to record, investigate, and respond to customer complaints.', evidence_requirement: 'Complaints register, investigation records, response letters', is_fundamental: false, display_order: 140 },
  { clause_number: '3.10', parent_clause_number: null, title: 'Traceability', description: 'The site shall be able to trace all raw materials from approved suppliers through processing to finished product dispatch.', evidence_requirement: 'Traceability procedure, traceability test records, mass balance', is_fundamental: true, display_order: 150 },
  { clause_number: '3.11', parent_clause_number: null, title: 'Customer Focus and Communication', description: 'Where customer-specific requirements exist, these shall be reviewed, understood, and communicated.', evidence_requirement: 'Customer requirement register, review records, communication logs', is_fundamental: false, display_order: 160 },

  // Section 4 — Site Standards
  { clause_number: '4.1', parent_clause_number: null, title: 'External Standards', description: 'The site shall be of suitable construction and maintained.', evidence_requirement: 'Site survey records, maintenance schedule, external inspection photos', is_fundamental: false, display_order: 170 },
  { clause_number: '4.2', parent_clause_number: null, title: 'Security', description: 'The site shall be secure and have procedures to manage access.', evidence_requirement: 'Site security policy, access log, visitor procedure', is_fundamental: false, display_order: 180 },
  { clause_number: '4.3', parent_clause_number: null, title: 'Layout, Product Flow and Segregation', description: 'The site shall have an appropriate layout and flow to prevent contamination.', evidence_requirement: 'Site layout plan, zoning map, segregation procedures', is_fundamental: false, display_order: 190 },
  { clause_number: '4.4', parent_clause_number: null, title: 'Utilities — Water, Ice, Air, Other Gases', description: 'All utilities used in the production area shall be monitored and controlled.', evidence_requirement: 'Water testing records, compressed air testing records, utilities policy', is_fundamental: false, display_order: 200 },
  { clause_number: '4.5', parent_clause_number: null, title: 'Equipment', description: 'Equipment shall be suitable for its intended purpose and maintained.', evidence_requirement: 'Equipment register, calibration schedule and records, maintenance log', is_fundamental: false, display_order: 210 },
  { clause_number: '4.6', parent_clause_number: null, title: 'Maintenance', description: 'The site shall have a planned maintenance programme for all equipment.', evidence_requirement: 'Planned maintenance schedule, completed maintenance records, contractor approvals', is_fundamental: false, display_order: 220 },
  { clause_number: '4.7', parent_clause_number: null, title: 'Staff Facilities', description: 'Adequate staff facilities shall be provided and maintained.', evidence_requirement: 'Inspection records for staff facilities, locker room photos, welfare procedure', is_fundamental: false, display_order: 230 },
  { clause_number: '4.8', parent_clause_number: null, title: 'Chemical and Physical Contamination Control', description: 'The site shall have controls in place to manage the risk of chemical and physical contamination.', evidence_requirement: 'Glass and brittle plastic register, chemical control procedure, contamination risk assessments', is_fundamental: false, display_order: 240 },
  { clause_number: '4.9', parent_clause_number: null, title: 'Housekeeping and Hygiene', description: 'There shall be documented cleaning and hygiene procedures.', evidence_requirement: 'Cleaning schedule, completed cleaning records, hygiene inspection records', is_fundamental: false, display_order: 250 },
  { clause_number: '4.10', parent_clause_number: null, title: 'Waste and Waste Disposal', description: 'Waste shall be removed regularly to prevent accumulation.', evidence_requirement: 'Waste management procedure, waste contractor records, waste transfer notes', is_fundamental: false, display_order: 260 },
  { clause_number: '4.11', parent_clause_number: null, title: 'Pest Control', description: 'The site shall have a pest control programme in place.', evidence_requirement: 'Pest control contract, service visit reports, bait station map, corrective actions', is_fundamental: false, display_order: 270 },

  // Section 5 — Product and Process Control
  { clause_number: '5.1', parent_clause_number: null, title: 'Product Design/Development', description: 'Product design and development shall be carried out in accordance with the HACCP study.', evidence_requirement: 'New product development records, trial records, HACCP review sign-off', is_fundamental: false, display_order: 280 },
  { clause_number: '5.2', parent_clause_number: null, title: 'Product Labelling', description: 'All products shall be correctly labelled in accordance with legal requirements.', evidence_requirement: 'Label approval records, regulatory review evidence, artwork sign-off', is_fundamental: false, display_order: 290 },
  { clause_number: '5.3', parent_clause_number: null, title: 'Management of Allergens', description: 'The site shall have a documented allergen management policy and procedure.', evidence_requirement: 'Allergen register, segregation procedures, allergen risk assessment, cleaning validation', is_fundamental: true, display_order: 300 },
  { clause_number: '5.4', parent_clause_number: null, title: 'Authenticity, Claims and Chain of Custody', description: 'The site shall have processes in place to minimise the risk of purchasing fraudulent material.', evidence_requirement: 'Vulnerability assessment, testing records, chain of custody certificates', is_fundamental: false, display_order: 310 },
  { clause_number: '5.5', parent_clause_number: null, title: 'Product Inspection and Laboratory Testing', description: 'Product shall be inspected and tested against specification.', evidence_requirement: 'Inspection records, laboratory test results, calibration certificates', is_fundamental: false, display_order: 320 },
  { clause_number: '5.6', parent_clause_number: null, title: 'Product Release', description: 'A procedure shall be in place to ensure product is released only when all quality checks have been completed.', evidence_requirement: 'Product release procedure, signed release records, QC check sheets', is_fundamental: false, display_order: 330 },

  // Section 6 — Process Control
  { clause_number: '6.1', parent_clause_number: null, title: 'Control of Operations', description: 'The site shall demonstrate that process controls are in place and effective.', evidence_requirement: 'Process control procedures, monitoring records, in-process check records', is_fundamental: false, display_order: 340 },
  { clause_number: '6.2', parent_clause_number: null, title: 'Quantity — Weight, Volume and Number Control', description: 'The site shall have a procedure to control quantity of product.', evidence_requirement: 'Weight control procedure, checkweigher records, statistical data', is_fundamental: false, display_order: 350 },
  { clause_number: '6.3', parent_clause_number: null, title: 'Calibration and Control of Measuring and Monitoring Devices', description: 'The site shall identify and control all measuring and monitoring devices.', evidence_requirement: 'Calibration register, calibration certificates, out-of-calibration investigation records', is_fundamental: false, display_order: 360 },

  // Section 7 — Personnel
  { clause_number: '7.1', parent_clause_number: null, title: 'Training — Raw Material Handling, Preparation, Processing, Packing and Storage Areas', description: 'All employees shall receive induction training and appropriate ongoing training.', evidence_requirement: 'Training matrix, completed training records, induction records, competence assessments', is_fundamental: false, display_order: 370 },
  { clause_number: '7.2', parent_clause_number: null, title: 'Personal Hygiene — All Production and Storage Areas', description: 'There shall be clear personal hygiene rules for all personnel.', evidence_requirement: 'Personal hygiene policy, signed employee declarations, hygiene audit records', is_fundamental: false, display_order: 380 },
  { clause_number: '7.3', parent_clause_number: null, title: 'Medical Screening', description: 'The site shall have a policy for medical screening of staff before working with food.', evidence_requirement: 'Medical screening policy, health declaration forms, occupational health records', is_fundamental: false, display_order: 390 },
  { clause_number: '7.4', parent_clause_number: null, title: 'Protective Clothing', description: 'All personnel working in production areas shall wear appropriate protective clothing.', evidence_requirement: 'PPE policy, clothing inspection records, laundry arrangements', is_fundamental: false, display_order: 400 },
];

// ── ISO 9001:2015 Quality Management — clause library (paraphrased summaries;
//    consult the published standard for authoritative text) ──────────────────
const ISO_9001_CLAUSES = [
  // Section 4 — Context of the Organization
  { clause_number: '4.1',   parent_clause_number: null,  title: 'Understanding the Organization and its Context', description: 'Determine the external and internal issues relevant to the organization\'s purpose that affect its ability to achieve the intended results of the QMS.', evidence_requirement: 'Context analysis (e.g. SWOT/PESTLE), issues log, strategic review minutes', is_fundamental: false, display_order: 10 },
  { clause_number: '4.2',   parent_clause_number: null,  title: 'Needs and Expectations of Interested Parties', description: 'Determine the interested parties relevant to the QMS and their requirements, and monitor and review this information.', evidence_requirement: 'Interested-parties register with requirements and review dates', is_fundamental: false, display_order: 20 },
  { clause_number: '4.3',   parent_clause_number: null,  title: 'Scope of the Quality Management System', description: 'Determine the boundaries and applicability of the QMS and maintain the scope as documented information, including justification for any requirement deemed not applicable.', evidence_requirement: 'Documented QMS scope statement with justified exclusions', is_fundamental: false, display_order: 30 },
  { clause_number: '4.4',   parent_clause_number: null,  title: 'QMS and its Processes', description: 'Establish, implement, maintain and continually improve the QMS, including the processes needed, their sequence, interaction, criteria, resources and risks.', evidence_requirement: 'Process map, process definitions/turtle diagrams, KPI criteria per process', is_fundamental: false, display_order: 40 },
  // Section 5 — Leadership
  { clause_number: '5.1',   parent_clause_number: null,  title: 'Leadership and Commitment', description: 'Top management shall demonstrate leadership and commitment to the QMS, including customer focus and promoting risk-based thinking.', evidence_requirement: 'Management review minutes, communicated objectives, resource decisions, leadership interviews', is_fundamental: false, display_order: 50 },
  { clause_number: '5.2',   parent_clause_number: null,  title: 'Quality Policy', description: 'Establish, implement and maintain a quality policy appropriate to the organisation, communicated, understood and available to interested parties.', evidence_requirement: 'Signed quality policy, communication evidence (noticeboards, inductions), review date', is_fundamental: false, display_order: 60 },
  { clause_number: '5.3',   parent_clause_number: null,  title: 'Roles, Responsibilities and Authorities', description: 'Assign, communicate and understand responsibilities and authorities for relevant roles, including QMS conformity and reporting on performance.', evidence_requirement: 'Organisation chart, role descriptions, appointment records', is_fundamental: false, display_order: 70 },
  // Section 6 — Planning
  { clause_number: '6.1',   parent_clause_number: null,  title: 'Actions to Address Risks and Opportunities', description: 'Determine risks and opportunities that need to be addressed and plan actions, their integration into QMS processes and evaluation of effectiveness.', evidence_requirement: 'Risk & opportunity register with actions, owners and effectiveness review', is_fundamental: false, display_order: 80 },
  { clause_number: '6.2',   parent_clause_number: null,  title: 'Quality Objectives and Planning to Achieve Them', description: 'Establish measurable quality objectives at relevant functions, levels and processes, with plans covering what, who, when, resources and evaluation.', evidence_requirement: 'Quality objectives with targets, action plans, progress reviews', is_fundamental: false, display_order: 90 },
  { clause_number: '6.3',   parent_clause_number: null,  title: 'Planning of Changes', description: 'Carry out changes to the QMS in a planned manner, considering purpose, consequences, integrity, resources and responsibilities.', evidence_requirement: 'Change requests/records showing planned implementation and review', is_fundamental: false, display_order: 100 },
  // Section 7 — Support
  { clause_number: '7.1',   parent_clause_number: null,  title: 'Resources', description: 'Determine and provide the resources needed for the QMS — people, infrastructure, environment for process operation, and organisational knowledge.', evidence_requirement: 'Resource plans, maintenance records, workplace environment checks', is_fundamental: false, display_order: 110 },
  { clause_number: '7.1.5', parent_clause_number: '7.1', title: 'Monitoring and Measuring Resources', description: 'Ensure monitoring and measuring resources are suitable, maintained and, where required, calibrated or verified against traceable standards.', evidence_requirement: 'Equipment register, calibration schedule, calibration certificates with traceability', is_fundamental: false, display_order: 120 },
  { clause_number: '7.2',   parent_clause_number: null,  title: 'Competence', description: 'Determine the necessary competence of persons doing work affecting quality performance, ensure competence on the basis of education, training or experience, and retain documented evidence.', evidence_requirement: 'Skills matrix with required competences per role, training records, competence assessments with assessor and date', is_fundamental: false, display_order: 130 },
  { clause_number: '7.3',   parent_clause_number: null,  title: 'Awareness', description: 'Ensure persons are aware of the quality policy, relevant objectives, their contribution to the QMS and the implications of not conforming.', evidence_requirement: 'Induction records, briefing/toolbox-talk records, awareness interview notes', is_fundamental: false, display_order: 140 },
  { clause_number: '7.4',   parent_clause_number: null,  title: 'Communication', description: 'Determine internal and external communications relevant to the QMS — what, when, with whom, how and who communicates.', evidence_requirement: 'Communication plan/matrix, meeting minutes, customer communication records', is_fundamental: false, display_order: 150 },
  { clause_number: '7.5',   parent_clause_number: null,  title: 'Documented Information', description: 'Create, update and control the documented information required by the standard and by the organisation, covering identification, format, review, approval, distribution and protection.', evidence_requirement: 'Document register with versions and review dates, controlled distribution, obsolete-document control', is_fundamental: false, display_order: 160 },
  // Section 8 — Operation
  { clause_number: '8.1',   parent_clause_number: null,  title: 'Operational Planning and Control', description: 'Plan, implement and control the processes needed to meet product and service requirements, including criteria, resources and control of planned and unintended changes.', evidence_requirement: 'Production plans, process control criteria, work instructions, change records', is_fundamental: false, display_order: 170 },
  { clause_number: '8.2',   parent_clause_number: null,  title: 'Requirements for Products and Services', description: 'Communicate with customers, determine and review requirements for products and services before committing to supply, and control changes to requirements.', evidence_requirement: 'Contract/order review records, customer requirement reviews, quotation records', is_fundamental: false, display_order: 180 },
  { clause_number: '8.3',   parent_clause_number: null,  title: 'Design and Development', description: 'Establish a design and development process with planning, inputs, controls (reviews, verification, validation), outputs and control of changes. Justify if not applicable.', evidence_requirement: 'Design plans, design reviews, verification/validation records, design change control (or justified exclusion in QMS scope)', is_fundamental: false, display_order: 190 },
  { clause_number: '8.4',   parent_clause_number: null,  title: 'Control of Externally Provided Processes, Products and Services', description: 'Ensure externally provided processes, products and services conform to requirements — supplier evaluation, selection, performance monitoring and re-evaluation.', evidence_requirement: 'Approved supplier list, supplier evaluations and re-evaluations, purchasing controls, incoming inspection records', is_fundamental: false, display_order: 200 },
  { clause_number: '8.5',   parent_clause_number: null,  title: 'Production and Service Provision', description: 'Implement controlled conditions for production and service provision, including identification and traceability, property of customers or suppliers, preservation and post-delivery activities.', evidence_requirement: 'Job/batch records, traceability records, customer-property log, preservation/handling controls', is_fundamental: false, display_order: 210 },
  { clause_number: '8.6',   parent_clause_number: null,  title: 'Release of Products and Services', description: 'Verify product and service requirements are met before release, with documented evidence of conformity and traceability to the person authorising release.', evidence_requirement: 'Inspection and test records, release authorisations with sign-off', is_fundamental: false, display_order: 220 },
  { clause_number: '8.7',   parent_clause_number: null,  title: 'Control of Nonconforming Outputs', description: 'Identify and control outputs that do not conform to requirements to prevent unintended use or delivery, and retain documented information on actions taken.', evidence_requirement: 'Non-conformance records with disposition, quarantine controls, concession records', is_fundamental: false, display_order: 230 },
  // Section 9 — Performance Evaluation
  { clause_number: '9.1',   parent_clause_number: null,  title: 'Monitoring, Measurement, Analysis and Evaluation', description: 'Determine what needs to be monitored and measured, the methods, and when; evaluate QMS performance and effectiveness including customer satisfaction and data analysis.', evidence_requirement: 'KPI dashboards, customer satisfaction data, trend analysis, evaluation records', is_fundamental: false, display_order: 240 },
  { clause_number: '9.2',   parent_clause_number: null,  title: 'Internal Audit', description: 'Conduct internal audits at planned intervals to verify the QMS conforms to requirements and is effectively implemented, with an audit programme, criteria, impartial auditors, reporting and follow-up.', evidence_requirement: 'Audit programme covering all processes, audit reports, auditor competence, corrective actions and close-out', is_fundamental: false, display_order: 250 },
  { clause_number: '9.3',   parent_clause_number: null,  title: 'Management Review', description: 'Top management shall review the QMS at planned intervals, covering the required inputs (audit results, performance, nonconformities, resources) and producing decisions on improvement and resource needs.', evidence_requirement: 'Management review agenda covering all required inputs, minutes, actions with owners', is_fundamental: false, display_order: 260 },
  // Section 10 — Improvement
  { clause_number: '10.1',  parent_clause_number: null,  title: 'Improvement — General', description: 'Determine and select opportunities for improvement and implement actions to meet customer requirements and enhance satisfaction.', evidence_requirement: 'Improvement log/projects, evidence of implemented improvements', is_fundamental: false, display_order: 270 },
  { clause_number: '10.2',  parent_clause_number: null,  title: 'Nonconformity and Corrective Action', description: 'React to nonconformities, evaluate the need for action to eliminate root causes, implement corrective action, review effectiveness and update risks where necessary.', evidence_requirement: 'NC/CAPA records with root cause analysis, corrective actions, effectiveness reviews', is_fundamental: false, display_order: 280 },
  { clause_number: '10.3',  parent_clause_number: null,  title: 'Continual Improvement', description: 'Continually improve the suitability, adequacy and effectiveness of the QMS using analysis, evaluation and management review outputs.', evidence_requirement: 'Trend data feeding improvement decisions, year-on-year objective performance', is_fundamental: false, display_order: 290 },
];

// ── ISO 14001:2015 Environmental Management — clause library ─────────────────
const ISO_14001_CLAUSES = [
  { clause_number: '4.1',   parent_clause_number: null,  title: 'Understanding the Organization and its Context', description: 'Determine external and internal issues, including environmental conditions, relevant to the organisation\'s purpose that affect the intended outcomes of the EMS.', evidence_requirement: 'Context analysis including environmental conditions, issues log', is_fundamental: false, display_order: 10 },
  { clause_number: '4.2',   parent_clause_number: null,  title: 'Needs and Expectations of Interested Parties', description: 'Determine interested parties, their relevant needs and expectations, and which become compliance obligations.', evidence_requirement: 'Interested-parties register including regulators and community', is_fundamental: false, display_order: 20 },
  { clause_number: '4.3',   parent_clause_number: null,  title: 'Scope of the Environmental Management System', description: 'Determine the boundaries and applicability of the EMS considering context, obligations, units, functions, activities, products and services, and maintain it as documented information.', evidence_requirement: 'Documented EMS scope statement', is_fundamental: false, display_order: 30 },
  { clause_number: '4.4',   parent_clause_number: null,  title: 'Environmental Management System', description: 'Establish, implement, maintain and continually improve the EMS, including the processes needed and their interactions.', evidence_requirement: 'EMS process map and documentation structure', is_fundamental: false, display_order: 40 },
  { clause_number: '5.1',   parent_clause_number: null,  title: 'Leadership and Commitment', description: 'Top management shall demonstrate leadership and commitment, take accountability for EMS effectiveness and integrate requirements into business processes.', evidence_requirement: 'Management review minutes, resourcing decisions, integration evidence', is_fundamental: false, display_order: 50 },
  { clause_number: '5.2',   parent_clause_number: null,  title: 'Environmental Policy', description: 'Establish an environmental policy including commitments to environmental protection, pollution prevention, fulfilling compliance obligations and continual improvement.', evidence_requirement: 'Signed environmental policy with the three commitments, communication evidence', is_fundamental: false, display_order: 60 },
  { clause_number: '5.3',   parent_clause_number: null,  title: 'Roles, Responsibilities and Authorities', description: 'Assign and communicate responsibilities and authorities for EMS conformance and performance reporting.', evidence_requirement: 'Organisation chart, EMS role descriptions', is_fundamental: false, display_order: 70 },
  { clause_number: '6.1.1', parent_clause_number: '6.1', title: 'Risks and Opportunities — General', description: 'Determine the risks and opportunities related to environmental aspects, compliance obligations and other issues that need to be addressed.', evidence_requirement: 'EMS risk & opportunity register', is_fundamental: false, display_order: 80 },
  { clause_number: '6.1.2', parent_clause_number: '6.1', title: 'Environmental Aspects', description: 'Determine the environmental aspects of activities, products and services that can be controlled or influenced, their impacts, and which are significant, considering a life-cycle perspective.', evidence_requirement: 'Aspects & impacts register with significance criteria and life-cycle consideration', is_fundamental: false, display_order: 90 },
  { clause_number: '6.1.3', parent_clause_number: '6.1', title: 'Compliance Obligations', description: 'Determine and have access to the compliance obligations related to environmental aspects and determine how they apply.', evidence_requirement: 'Legal & other requirements register with applicability and access to current texts', is_fundamental: false, display_order: 100 },
  { clause_number: '6.1.4', parent_clause_number: '6.1', title: 'Planning Action', description: 'Plan actions to address significant aspects, compliance obligations, and risks and opportunities, integrated into EMS processes with effectiveness evaluation.', evidence_requirement: 'Action plans linked to the aspects register and obligations', is_fundamental: false, display_order: 110 },
  { clause_number: '6.2',   parent_clause_number: null,  title: 'Environmental Objectives and Planning', description: 'Establish measurable environmental objectives considering significant aspects and compliance obligations, with plans for achieving them and indicators for monitoring.', evidence_requirement: 'Environmental objectives with targets, plans, monitoring indicators', is_fundamental: false, display_order: 120 },
  { clause_number: '7.1',   parent_clause_number: null,  title: 'Resources', description: 'Determine and provide the resources needed for the EMS.', evidence_requirement: 'Budget/resource allocations for environmental controls and monitoring', is_fundamental: false, display_order: 130 },
  { clause_number: '7.2',   parent_clause_number: null,  title: 'Competence', description: 'Determine the necessary competence of persons whose work affects environmental performance and the ability to fulfil compliance obligations, and retain documented evidence.', evidence_requirement: 'Skills matrix covering environmentally-critical roles, training and competence records', is_fundamental: false, display_order: 140 },
  { clause_number: '7.3',   parent_clause_number: null,  title: 'Awareness', description: 'Ensure persons are aware of the environmental policy, significant aspects related to their work, their contribution, and implications of not conforming.', evidence_requirement: 'Induction/awareness training records, briefing records', is_fundamental: false, display_order: 150 },
  { clause_number: '7.4',   parent_clause_number: null,  title: 'Communication', description: 'Establish processes for internal and external communications relevant to the EMS, including responding to relevant communications on the EMS.', evidence_requirement: 'Communication procedure, external enquiry/complaint responses', is_fundamental: false, display_order: 160 },
  { clause_number: '7.5',   parent_clause_number: null,  title: 'Documented Information', description: 'Create, update and control documented information required by the standard and determined as necessary for EMS effectiveness.', evidence_requirement: 'Document register, controlled procedures, record retention', is_fundamental: false, display_order: 170 },
  { clause_number: '8.1',   parent_clause_number: null,  title: 'Operational Planning and Control', description: 'Establish operating criteria and controls for processes associated with significant aspects and compliance obligations, including control of outsourced processes and life-cycle considerations.', evidence_requirement: 'Operational control procedures (waste, emissions, storage), contractor controls, procurement criteria', is_fundamental: false, display_order: 180 },
  { clause_number: '8.2',   parent_clause_number: null,  title: 'Emergency Preparedness and Response', description: 'Prepare for and respond to potential environmental emergency situations, including periodic testing of planned response actions where practicable.', evidence_requirement: 'Emergency plans (spills, fire water), drill/test records, spill kit inspections', is_fundamental: false, display_order: 190 },
  { clause_number: '9.1.1', parent_clause_number: '9.1', title: 'Monitoring, Measurement, Analysis and Evaluation', description: 'Monitor, measure, analyse and evaluate environmental performance using calibrated or verified equipment where relevant, and communicate performance internally and externally as required.', evidence_requirement: 'Monitoring data (energy, water, waste, emissions), calibrated monitoring equipment records', is_fundamental: false, display_order: 200 },
  { clause_number: '9.1.2', parent_clause_number: '9.1', title: 'Evaluation of Compliance', description: 'Evaluate fulfilment of compliance obligations at a planned frequency, take action if needed, and maintain knowledge and understanding of compliance status.', evidence_requirement: 'Compliance evaluation schedule and records, permit condition checks', is_fundamental: false, display_order: 210 },
  { clause_number: '9.2',   parent_clause_number: null,  title: 'Internal Audit', description: 'Conduct internal EMS audits at planned intervals with an audit programme considering environmental importance of processes and results of previous audits.', evidence_requirement: 'Audit programme, audit reports, close-out of findings', is_fundamental: false, display_order: 220 },
  { clause_number: '9.3',   parent_clause_number: null,  title: 'Management Review', description: 'Top management shall review the EMS at planned intervals covering required inputs including compliance status, aspects performance and adequacy of resources.', evidence_requirement: 'Management review minutes covering all required inputs, actions', is_fundamental: false, display_order: 230 },
  { clause_number: '10.1',  parent_clause_number: null,  title: 'Improvement — General', description: 'Determine opportunities for improvement and implement actions to achieve the intended outcomes of the EMS.', evidence_requirement: 'Improvement log with environmental improvements', is_fundamental: false, display_order: 240 },
  { clause_number: '10.2',  parent_clause_number: null,  title: 'Nonconformity and Corrective Action', description: 'React to nonconformities including mitigating environmental impacts, evaluate the need to eliminate root causes and review effectiveness of corrective actions.', evidence_requirement: 'Environmental NC/CAPA records with root cause and effectiveness review', is_fundamental: false, display_order: 250 },
  { clause_number: '10.3',  parent_clause_number: null,  title: 'Continual Improvement', description: 'Continually improve the suitability, adequacy and effectiveness of the EMS to enhance environmental performance.', evidence_requirement: 'Year-on-year performance trends, improvement outcomes', is_fundamental: false, display_order: 260 },
];

// ── ISO 45001:2018 Occupational Health & Safety — clause library ──────────────
const ISO_45001_CLAUSES = [
  { clause_number: '4.1',   parent_clause_number: null,  title: 'Understanding the Organization and its Context', description: 'Determine external and internal issues relevant to the organisation\'s purpose that affect its ability to achieve the intended outcomes of the OH&S management system.', evidence_requirement: 'Context analysis, issues log', is_fundamental: false, display_order: 10 },
  { clause_number: '4.2',   parent_clause_number: null,  title: 'Needs and Expectations of Workers and Other Interested Parties', description: 'Determine the interested parties relevant to the OH&S system — including workers — and their relevant needs and expectations, and which become legal and other requirements.', evidence_requirement: 'Interested-parties register including worker representation', is_fundamental: false, display_order: 20 },
  { clause_number: '4.3',   parent_clause_number: null,  title: 'Scope of the OH&S Management System', description: 'Determine the boundaries and applicability of the OH&S management system, including activities, products and services within the organisation\'s control or influence that can impact OH&S performance.', evidence_requirement: 'Documented OH&S scope statement', is_fundamental: false, display_order: 30 },
  { clause_number: '4.4',   parent_clause_number: null,  title: 'OH&S Management System', description: 'Establish, implement, maintain and continually improve the OH&S management system, including the needed processes and their interactions.', evidence_requirement: 'OH&S system documentation structure and process map', is_fundamental: false, display_order: 40 },
  { clause_number: '5.1',   parent_clause_number: null,  title: 'Leadership and Commitment', description: 'Top management shall take overall responsibility for the prevention of work-related injury and ill health, provide safe and healthy workplaces, and lead a culture supporting the OH&S system.', evidence_requirement: 'Leadership tours/inspections, resourcing decisions, culture initiatives', is_fundamental: false, display_order: 50 },
  { clause_number: '5.2',   parent_clause_number: null,  title: 'OH&S Policy', description: 'Establish an OH&S policy committing to safe and healthy working conditions, eliminating hazards, fulfilling legal requirements and consultation and participation of workers.', evidence_requirement: 'Signed OH&S policy with required commitments, communication evidence', is_fundamental: false, display_order: 60 },
  { clause_number: '5.3',   parent_clause_number: null,  title: 'Roles, Responsibilities and Authorities', description: 'Assign and communicate responsibilities and authorities for relevant roles within the OH&S management system at all levels.', evidence_requirement: 'Organisation chart, OH&S responsibilities in role descriptions', is_fundamental: false, display_order: 70 },
  { clause_number: '5.4',   parent_clause_number: null,  title: 'Consultation and Participation of Workers', description: 'Establish processes for consultation and participation of workers at all levels in the development, planning, implementation and evaluation of the OH&S system, removing barriers to participation.', evidence_requirement: 'Safety committee minutes, worker consultation records, participation mechanisms', is_fundamental: false, display_order: 80 },
  { clause_number: '6.1.1', parent_clause_number: '6.1', title: 'Risks and Opportunities — General', description: 'Determine the risks and opportunities to the OH&S system that need to be addressed, maintaining documented information on them and the processes used.', evidence_requirement: 'OH&S risk & opportunity register', is_fundamental: false, display_order: 90 },
  { clause_number: '6.1.2', parent_clause_number: '6.1', title: 'Hazard Identification and Assessment of Risks', description: 'Establish ongoing and proactive processes for hazard identification (including routine and non-routine activities, human factors, past incidents) and assessment of OH&S risks and opportunities.', evidence_requirement: 'Risk assessments/HIRA, hazard reporting records, review after incidents or change', is_fundamental: false, display_order: 100 },
  { clause_number: '6.1.3', parent_clause_number: '6.1', title: 'Determination of Legal and Other Requirements', description: 'Determine and have access to up-to-date legal requirements and other requirements applicable to hazards, OH&S risks and the OH&S system, and determine how they apply.', evidence_requirement: 'Legal register with applicability, update mechanism', is_fundamental: false, display_order: 110 },
  { clause_number: '6.1.4', parent_clause_number: '6.1', title: 'Planning Action', description: 'Plan actions to address risks, opportunities, legal requirements and emergency preparedness, integrated into system processes, considering the hierarchy of controls.', evidence_requirement: 'Action plans referencing the hierarchy of controls', is_fundamental: false, display_order: 120 },
  { clause_number: '6.2',   parent_clause_number: null,  title: 'OH&S Objectives and Planning', description: 'Establish measurable OH&S objectives considering assessment results and consultation with workers, with plans covering actions, resources, responsibilities, timescales and evaluation.', evidence_requirement: 'OH&S objectives with targets, plans and progress reviews', is_fundamental: false, display_order: 130 },
  { clause_number: '7.1',   parent_clause_number: null,  title: 'Resources', description: 'Determine and provide the resources needed to establish, implement, maintain and continually improve the OH&S management system.', evidence_requirement: 'Budget for controls, PPE and monitoring; resourcing decisions', is_fundamental: false, display_order: 140 },
  { clause_number: '7.2',   parent_clause_number: null,  title: 'Competence', description: 'Determine the competence of workers that affects OH&S performance, ensure competence including the ability to identify hazards, and retain documented evidence.', evidence_requirement: 'Skills matrix for safety-critical tasks and licences (forklift, working at height, first aid), training and competence records with expiry dates', is_fundamental: false, display_order: 150 },
  { clause_number: '7.3',   parent_clause_number: null,  title: 'Awareness', description: 'Make workers aware of the OH&S policy and objectives, hazards and risks relevant to them, their contribution, and their ability to remove themselves from imminent danger without reprisal.', evidence_requirement: 'Induction records, hazard awareness briefings, stop-work authority communication', is_fundamental: false, display_order: 160 },
  { clause_number: '7.4',   parent_clause_number: null,  title: 'Communication', description: 'Establish processes for internal and external OH&S communications, taking into account diversity aspects (language, literacy, disability) and the views of external interested parties.', evidence_requirement: 'Communication plan, multilingual/accessible safety information where relevant', is_fundamental: false, display_order: 170 },
  { clause_number: '7.5',   parent_clause_number: null,  title: 'Documented Information', description: 'Create, update and control the documented information required by the standard and necessary for OH&S system effectiveness.', evidence_requirement: 'Document register, controlled safe systems of work, record retention', is_fundamental: false, display_order: 180 },
  { clause_number: '8.1.1', parent_clause_number: '8.1', title: 'Operational Planning and Control — General', description: 'Plan, implement, control and maintain the processes needed to meet OH&S requirements, establishing criteria and adapting work to workers, coordinating with other employers on multi-employer workplaces.', evidence_requirement: 'Safe systems of work, permits to work, coordination arrangements', is_fundamental: false, display_order: 190 },
  { clause_number: '8.1.2', parent_clause_number: '8.1', title: 'Eliminating Hazards and Reducing OH&S Risks', description: 'Establish processes for the elimination of hazards and reduction of OH&S risks using the hierarchy of controls: eliminate, substitute, engineering controls, administrative controls, PPE.', evidence_requirement: 'Risk assessments showing hierarchy applied, engineering control records, PPE as last resort', is_fundamental: false, display_order: 200 },
  { clause_number: '8.1.3', parent_clause_number: '8.1', title: 'Management of Change', description: 'Establish processes for the implementation and control of planned temporary and permanent changes that impact OH&S performance, reviewing unintended consequences.', evidence_requirement: 'Management-of-change records with OH&S review', is_fundamental: false, display_order: 210 },
  { clause_number: '8.1.4', parent_clause_number: '8.1', title: 'Procurement, Contractors and Outsourcing', description: 'Control procurement of products and services to ensure conformity; coordinate with contractors to identify hazards and control risks; ensure outsourced functions are controlled.', evidence_requirement: 'Contractor approval and induction records, procurement OH&S criteria, outsourcing controls', is_fundamental: false, display_order: 220 },
  { clause_number: '8.2',   parent_clause_number: null,  title: 'Emergency Preparedness and Response', description: 'Establish, test and revise planned responses to potential emergency situations, including first aid, training, communication to workers and relevant interested parties.', evidence_requirement: 'Emergency plans, drill records, first-aider register with in-date certificates', is_fundamental: false, display_order: 230 },
  { clause_number: '9.1.1', parent_clause_number: '9.1', title: 'Monitoring, Measurement, Analysis and Performance Evaluation', description: 'Determine what needs monitoring (legal compliance, activities related to hazards, progress on objectives, operational controls), methods and criteria; calibrate or verify measuring equipment.', evidence_requirement: 'Inspection schedules and records, exposure monitoring, calibrated equipment records', is_fundamental: false, display_order: 240 },
  { clause_number: '9.1.2', parent_clause_number: '9.1', title: 'Evaluation of Compliance', description: 'Evaluate compliance with legal and other requirements at a planned frequency, act as needed and maintain knowledge of compliance status.', evidence_requirement: 'Compliance evaluation records against the legal register', is_fundamental: false, display_order: 250 },
  { clause_number: '9.2',   parent_clause_number: null,  title: 'Internal Audit', description: 'Conduct internal OH&S audits at planned intervals with an impartial programme, reporting results to relevant workers and their representatives.', evidence_requirement: 'Audit programme, reports, communication of results to workers, close-out', is_fundamental: false, display_order: 260 },
  { clause_number: '9.3',   parent_clause_number: null,  title: 'Management Review', description: 'Top management shall review the OH&S system at planned intervals, covering required inputs including incidents, consultation, risks and opportunities, and communicating relevant outputs to workers.', evidence_requirement: 'Management review minutes covering all required inputs, outputs communicated', is_fundamental: false, display_order: 270 },
  { clause_number: '10.1',  parent_clause_number: null,  title: 'Improvement — General', description: 'Determine opportunities for improvement and implement necessary actions to achieve the intended outcomes of the OH&S management system.', evidence_requirement: 'Improvement log with OH&S improvements', is_fundamental: false, display_order: 280 },
  { clause_number: '10.2',  parent_clause_number: null,  title: 'Incident, Nonconformity and Corrective Action', description: 'React in a timely manner to incidents and nonconformities, investigate with worker participation, determine root causes, assess related risks, act and review effectiveness.', evidence_requirement: 'Incident investigations with root cause, corrective actions, effectiveness reviews, worker involvement', is_fundamental: false, display_order: 290 },
  { clause_number: '10.3',  parent_clause_number: null,  title: 'Continual Improvement', description: 'Continually improve the suitability, adequacy and effectiveness of the OH&S system — enhancing performance, promoting culture and participation, and communicating results to workers.', evidence_requirement: 'Performance trends, culture/participation initiatives, communicated results', is_fundamental: false, display_order: 300 },
];

// ── Library map — a standard is seedable only when it has an entry here ──────
const CLAUSE_LIBRARIES = {
  brcgs_packaging: { issue: '7',    clauses: BRCGS_PACKAGING_CLAUSES },
  iso_9001:        { issue: '2015', clauses: ISO_9001_CLAUSES },
  iso_14001:       { issue: '2015', clauses: ISO_14001_CLAUSES },
  iso_45001:       { issue: '2018', clauses: ISO_45001_CLAUSES },
};

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);
  const user = await base44.auth.me();

  if (!user || user.role !== 'admin') {
    return Response.json({ error: 'Forbidden: Admin access required' }, { status: 403 });
  }

  const body = await req.json().catch(() => ({}));
  const standard = body.standard || 'brcgs_packaging';

  const library = CLAUSE_LIBRARIES[standard];
  if (!library) {
    return Response.json({
      success: false,
      message: `No clause library exists for ${standard} yet. Available: ${Object.keys(CLAUSE_LIBRARIES).join(', ')}.`,
    }, { status: 422 });
  }
  const issue_number = body.issue_number || library.issue;

  // Idempotency check — don't seed if clauses already exist for this standard
  const existing = await base44.asServiceRole.entities.BRCClause.filter({ standard }, '-created_date', 1);
  if (existing.length > 0) {
    return Response.json({
      success: false,
      message: `Clauses for ${standard} already exist (${existing.length}+ records). Use force:true to re-seed.`,
      count: existing.length,
    });
  }

  // Force re-seed if requested
  if (body.force) {
    const allExisting = await base44.asServiceRole.entities.BRCClause.filter({ standard }, 'display_order', 500);
    for (const c of allExisting) {
      await base44.asServiceRole.entities.BRCClause.delete(c.id);
    }
  }

  // Bulk create
  const records = library.clauses.map(c => ({
    ...c,
    standard,
    issue_number,
  }));

  // Create in batches of 10
  const results = [];
  for (let i = 0; i < records.length; i += 10) {
    const batch = records.slice(i, i + 10);
    const created = await base44.asServiceRole.entities.BRCClause.bulkCreate(batch);
    results.push(...created);
  }

  return Response.json({
    success: true,
    standard,
    issue_number,
    seeded: results.length,
    message: `Successfully seeded ${results.length} clauses for ${standard} (${issue_number}).`,
  });
});